[defaults]
cct_min = 3200
cct_max = 5600
rgb = true
scenes = true
cct_split_packets = false
reports_status = true

[[model]]
patterns = ["Apollo"]
cct_min = 5600
cct_max = 5600
rgb = false
scenes = false
cct_split_packets = true

[[model]]
patterns = ["GL1"]
cct_min = 2900
cct_max = 7000
rgb = false
scenes = false
cct_split_packets = true

[[model]]
patterns = ["NL140", "SNL1320", "SNL1920", "SNL480", "SNL530", "SNL660", "SNL960", "SRP16", "SRP18", "WRP18", "ZRP16"]
rgb = false
scenes = false
cct_split_packets = true

[[model]]
patterns = ["BH30S", "CL124", "RGB C80", "RGB CB60", "RGB1000", "RGB1200", "RGB140", "RGB176 A1", "RGB512", "RGB800", "SL-90"]
cct_min = 2500
cct_max = 10000

[[model]]
patterns = ["CB60"]
cct_min = 2500
cct_max = 6500

[[model]]
patterns = ["RGB168"]
cct_min = 2500
cct_max = 8500

[[model]]
patterns = ["RGB176"]
reports_status = false

[[model]]
patterns = ["RGB1", "RGB18", "RGB190", "RGB450", "RGB480", "RGB530PRO", "RGB530", "RGB650", "RGB660PRO", "RGB660", "RGB960", "RGB-P200", "RGB-P280"]

[[model]]
patterns = ["SL70", "SL80"]
cct_max = 8500

[[model]]
patterns = ["ZK-RY"]
cct_min = 5600
cct_max = 5600
